#!/bin/sh

# TODO(axw) lock this down to only those users managed by the git service.
cp /home/ubuntu/.ssh/authorized_keys /home/$1/.ssh/admin_authorized_keys
chown $1:$1 /home/$1/.ssh/admin_authorized_keys
exit 1 # continue on with normal authorization process

